#!/bin/sh

# 用 `` 可以将命令的输出结果赋值给变量
# 获取当前提交的 commit msg
commit_msg=`cat $1`

log_msg="feature"

if [[  "$commit_msg" != "$log_msg" ]];
then
	echo "\n不合法的 commit 消息提交格式！！！请使用正确的格式"

	# 异常退出
	exit 1
else
	echo "相等"
fi
